# Generated by Django 5.1.1 on 2024-11-18 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='receita',
        ),
        migrations.CreateModel(
            name='EstoqueChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo_alteracao', models.CharField(choices=[('adicao', 'Adição'), ('venda', 'Venda')], max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alterada', models.IntegerField()),
                ('tipo_alteracao', models.CharField(choices=[('adicao', 'Adição'), ('venda', 'Venda')], max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='ItemReceita',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
