# Generated by Django 5.1.1 on 2024-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_paginainicial_produtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginainicial',
            old_name='imagem',
            new_name='imagem_fundo',
        ),
        migrations.RemoveField(
            model_name='paginainicial',
            name='descricao',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='link_login_gerente',
            field=models.URLField(default='/login/gerente/'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='link_login_produtor',
            field=models.URLField(default='/login/produtor/'),
        ),
    ]
