# Generated by Django 5.1.1 on 2024-11-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_imagem_paginainicial_imagem_fundo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_login', models.CharField(choices=[('gerente', 'Login Gerente'), ('produtor', 'Login Produtor')], max_length=10, unique=True)),
                ('titulo', models.CharField(default='Bem-vindo', max_length=200)),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='link_login_gerente',
            field=models.CharField(default='/login/gerente/', max_length=200),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='link_login_produtor',
            field=models.CharField(default='/login/produtor/', max_length=200),
        ),
    ]
