# Generated by Django 5.1.1 on 2024-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_conteudologin_alter_paginainicial_link_login_gerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudologin',
            name='tipo_login',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conteudologin',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
