# Generated by Django 5.1.1 on 2024-11-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_conteudologin_tipo_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
    ]
